### ISSUE TITLE
Consider detaching the fork

### ISSUE THREAD

**Issue by Samyak2** [aditeyabaral/NLPC#13]
This repo currently is listed as a fork. You should consider detaching your fork from the original repo, this will keep all of the commits from the original repo but will make your fork a normal repository.

Reasons for doing so:

- Commits/PRs made to a fork do not count towards individual contributions [1]
- The original repo does not seem to be maintained

[[1]](https://docs.github.com/en/github/setting-up-and-managing-your-github-profile/why-are-my-contributions-not-showing-up-on-my-profile#commit-was-made-in-a-fork) - this also has instructions to convert your fork to a standalone repository. You will have to contact GitHub support to do so, they reply within a few hours.

**Comment by aditeyabaral** [comment]
Sorry for the delay lol.
Just raised the ticket for the same :smiley:
