### ISSUE TITLE
Save and Load model for Lemmatizer

### ISSUE THREAD

**Issue by aditeyabaral** [aditeyabaral/NLPC#8]
The lemmatizer uses a dataset of given words and their lemma and stores this in a hashtable. It would be great if this hashtable could be saved locally on a file (without the dataset) and loaded when the lemmatizer is initialised. It would drastically reduce time taken to initialise it since it would remove the time taken to read and construct the hashtable from the dataset.

**Comment by anihm136** [comment]
I'd like to work on this

**Comment by aditeyabaral** [comment]
Sure, go ahead 👍
